name: Deploy Browser Extension

on:
  push:
    tags:
      - 'ecu-test-diff-[0-9]*.[0-9]*.[0-9]*'
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEPLOYMENT: 'False'

jobs:
  version-check:
    runs-on: ubuntu-latest
    if: |
      startsWith(github.ref, 'refs/tags/ecu-test-diff-') ||
      github.event_name == 'release'
    outputs:
      proceed: ${{ steps.version-check.outputs.proceed }}
    steps:
      - uses: actions/checkout@v4
      - name: Check tag matches manifest version
        id: version-check
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

          # Tag ref of release refs/tags/<tag_name> as well
          TAG_VERSION="${GITHUB_REF#refs/tags/ecu-test-diff-}"
          MANIFEST_VERSION=$(jq -r '.version' static/manifest.json)
          echo "Tag version: $TAG_VERSION"
          echo "Manifest version: $MANIFEST_VERSION"

          if [ "$TAG_VERSION" != "$MANIFEST_VERSION" ]; then
            echo "❌ Tag version ($TAG_VERSION) does not match manifest version ($MANIFEST_VERSION)."
            echo "proceed=false" >> $GITHUB_OUTPUT
            exit 1
          elif [[ "{{ github.event_name }}" == "release" ]]; then
            ]]
          fi

          echo "✅ Tag version matches manifest version."
          echo "proceed=true" >> $GITHUB_OUTPUT

  build:
    needs: version-check
    if: needs.version-check.outputs.proceed == 'true'
    uses: ./.github/workflows/build.yml

  publish:
    needs: [version-check, build]
    if: ${{ github.env.DEPLOYMENT == 'True' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ['chrome'] # After supporting multiple browsers, this will be changed to ["chrome", "firefox"]
    steps:
      - name: Get artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.browser }}-extension
      - name: Publish to Firefox Add-on
        if: ${{ matrix.browser == 'firefox' }}
        run: echo "Publishing to Firefox Add-on is not implemented yet."
      - name: Publish to Chrome Web Store
        if: ${{ matrix.browser == 'chrome' }}
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: ${{ matrix.browser }}-extension.zip
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }} # or "trustedTesters" for internal testing
