name: REUSE Compliance Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  reuse-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v5

      - name: REUSE SPDX SBOM
        uses: fsfe/reuse-action@v5
        with:
          args: spdx -o sbom.spdx

      - name: Upload spdx
        uses: actions/upload-artifact@v4
        with:
          name: spdx-sbom
          path: sbom.spdx
          if-no-files-found: error
